'use client'
import { usePathname } from 'next/navigation';
import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathName = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <div className="header" style={{ marginBottom: 10 }}>
            This is header bar.
          </div>

          <ul style={{ alignContent: 'center' }}>
            <li>
              <Link href="product" style={{ padding: 3, margin: 1, backgroundColor: '#dedede', color: pathName.endsWith('product') ? 'green' :'black'}}>
                Product List
              </Link>
              <Link href="product/detail" style={{ padding: 3, margin: 1, backgroundColor: '#dedede', color: pathName.endsWith('product/detail') ? 'green' :'black' }}>
                Product Detail
              </Link>
              <Link href="about" style={{ padding: 3, margin: 1, backgroundColor: '#dedede', color: pathName.endsWith('about') ? 'green' :'black' }}>
                About
              </Link>
            </li>
          </ul>
        </div>
        {children}
        <div className="footer" style={{ marginTop: 10 }}>
          This is footer area.
        </div>
      </body>
    </html>
  );
}
